// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PhillipScottGivens.Library.AppSessionFramework.Generators
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.Reflection;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class SessionProxyEmitter : SessionProxyEmitterBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 8 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
 
public void T4EmitConstructor(string constructorDefinition)
{

        
        #line default
        #line hidden
        
        #line 12 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(constructorDefinition));

        
        #line default
        #line hidden
        
        #line 12 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write("\r\n{\r\n\tOnConstructed();\t\r\n}\r\n");

        
        #line default
        #line hidden
        
        #line 16 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
 
}

private void T4EmitVoidOperation(MethodInfo method)
{

        
        #line default
        #line hidden
        
        #line 21 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write("// Generated by SessionProxyEmitter.EmitVoidOperation\r\n");

        
        #line default
        #line hidden
        
        #line 23 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(code.OverrideMethodSignature(method)));

        
        #line default
        #line hidden
        
        #line 23 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write("\r\n{\r\n\tbase.ExecuteOperation(\"");

        
        #line default
        #line hidden
        
        #line 25 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));

        
        #line default
        #line hidden
        
        #line 25 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write("\", () => ");

        
        #line default
        #line hidden
        
        #line 25 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(code.CallBaseMethod(method)));

        
        #line default
        #line hidden
        
        #line 25 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write(");\r\n}\t\r\n");

        
        #line default
        #line hidden
        
        #line 27 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
 
}
private void T4EmitTypeOperation(MethodInfo method)
{

        
        #line default
        #line hidden
        
        #line 31 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write("// Generated by SessionProxyEmitter.T4EmitTypeOperation\r\n");

        
        #line default
        #line hidden
        
        #line 33 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(code.OverrideMethodSignature(method)));

        
        #line default
        #line hidden
        
        #line 33 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write("\r\n{\r\n\tOnOperationBegin(\"");

        
        #line default
        #line hidden
        
        #line 35 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));

        
        #line default
        #line hidden
        
        #line 35 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write("\");\r\n\t");

        
        #line default
        #line hidden
        
        #line 36 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(code.GetCSharpTypeName(method.ReturnType)));

        
        #line default
        #line hidden
        
        #line 36 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write(" value = default(");

        
        #line default
        #line hidden
        
        #line 36 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(code.GetCSharpTypeName(method.ReturnType)));

        
        #line default
        #line hidden
        
        #line 36 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write(");\r\n\ttry\r\n\t{\r\n    \tvalue = ");

        
        #line default
        #line hidden
        
        #line 39 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(code.CallBaseMethod(method)));

        
        #line default
        #line hidden
        
        #line 39 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write(";\r\n\t\tOnOperationSuccess(\"");

        
        #line default
        #line hidden
        
        #line 40 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));

        
        #line default
        #line hidden
        
        #line 40 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write("\");\r\n\t}\r\n\tcatch(Exception e)\r\n\t{\r\n\t\tOnOperationError(\"");

        
        #line default
        #line hidden
        
        #line 44 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));

        
        #line default
        #line hidden
        
        #line 44 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write("\", e);\r\n\t}\t\t\r\n\treturn value;\r\n}\t\r\n");

        
        #line default
        #line hidden
        
        #line 48 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
 
}

internal void T4EmitDataProperty(PropertyInfo property, string setAccessor)
{

        
        #line default
        #line hidden
        
        #line 53 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write("// Generated by SessionProxyEmitter.T4EmitDataProperty\r\n// Proxy commented out be" +
        "cause no value is addded. To add code to \r\n// this property, go to SessionProxyE" +
        "mitter.tt T4EmitDataProperty\r\n// and add the code there. \r\n//");

        
        #line default
        #line hidden
        
        #line 58 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(code.OverridePropertySignature(property)));

        
        #line default
        #line hidden
        
        #line 58 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write("\r\n//{\r\n//\tget\r\n//\t{\r\n//\t\treturn base.");

        
        #line default
        #line hidden
        
        #line 62 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));

        
        #line default
        #line hidden
        
        #line 62 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write(";\r\n//\t}\r\n//\t");

        
        #line default
        #line hidden
        
        #line 64 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(setAccessor));

        
        #line default
        #line hidden
        
        #line 64 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write("set\r\n//\t{\r\n//\t\tbase.");

        
        #line default
        #line hidden
        
        #line 66 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));

        
        #line default
        #line hidden
        
        #line 66 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
this.Write(" = value;\r\n//\t}\r\n//}\r\n");

        
        #line default
        #line hidden
        
        #line 69 "C:\R2\Components\AppSessionFramework\Library.AppSessionFramework.Generators\SessionProxyEmitter.tt"
 
}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class SessionProxyEmitterBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
